"""
Project Argus - State Definitions

Defines the `AgentState` TypedDict (the "nervous system") and 
Pydantic models for structured LLM outputs.
"""

import operator
from typing import Annotated, TypedDict, List, Literal
from pydantic import BaseModel, Field


class AgentState(TypedDict):
    """
    The shared memory of the agent graph.
    
    Attributes:
        query: The user's original research question.
        plan: A list of specific search queries generated by the Librarian.
        scraped_data: Raw text chunks scraped from the web (append-only).
        structured_evidence: Trusted facts extracting by the Refiner.
        source_map: Mapping of source_id -> {url, title, snippet} for citations.
        critique: Feedback from the Fact-Checker node.
        report: The final markdown report generated by the Ghostwriter.
        re_search_required: Boolean flag triggering a feedback loop.
        active_node: Track which node is currently executing (for UI).
    """
    query: str
    plan: List[str]
    scraped_data: Annotated[List[dict], operator.add]
    structured_evidence: List[dict]
    source_map: dict
    critique: str
    report: str
    re_search_required: bool
    verified_facts: List[dict]
    iteration_count: int  # Loop-safety counter for fact-checker re-search cycles
    active_node: str


# ── Pydantic Models for Structured Output ────────────────────────────────────

class VerifiedFact(BaseModel):
    claim: str
    source_url: str
    source_excerpt: str
    support_level: Literal["SUPPORTED", "PARTIALLY_SUPPORTED", "NOT_SUPPORTED", "UNCERTAIN"]
    confidence: float

class VerifiedFactBatch(BaseModel):
    """Batch of verified facts — returned by a single LLM call."""
    results: List[VerifiedFact] = Field(
        description="List of verified facts with support levels and confidence scores."
    )

class ResearchPlan(BaseModel):
    """Output schema for the Librarian node."""
    search_queries: List[str] = Field(
        description="List of 3-5 highly specific search queries to gather information."
    )


class FactCheckResult(BaseModel):
    """Output schema for the Critic node."""
    re_search_required: bool = Field(
        description="True if important information is missing or conflicting."
    )
    critique: str = Field(
        description="Explanation of what is missing or why re-search is needed."
    )
