"""
Defines the `AgentState` TypedDict shared across graph nodes and the
Pydantic models for structured LLM outputs.
"""

import operator
from typing import Annotated, TypedDict, List, Literal
from pydantic import BaseModel, ConfigDict, Field


class AgentState(TypedDict):
    """
    The shared memory of the agent graph.

    Attributes:
        session_id: Unique id for this research run. Scopes KG fact retrieval so
            the Critic/Reflector reason only over facts gathered in THIS run,
            preventing cross-run contamination of gap analysis.
        query: The user's original research question.
        plan: The search queries Scout runs next — set by the Librarian, then
            replaced each loop iteration by the Critic/Reflector's follow-ups.
        original_plan: The Librarian's plan, set once and never overwritten —
            lets the Critic measure coverage against the original sub-questions
            even after `plan` has moved on to follow-up queries.
        scraped_data: Raw text chunks scraped from the web (append-only).
        structured_evidence: Trusted facts extracting by the Refiner.
        source_map: Mapping of source_id -> {url, title, snippet} for citations.
        backend_health: Per-retrieval-backend call/result counts for the run,
            with `degraded` set for any backend that returned nothing at all.
        critique: Feedback from the Fact-Checker node.
        report: The final markdown report generated by the Ghostwriter.
        re_search_required: Boolean flag triggering a feedback loop.
        knowledge_gap_detected: Boolean flag indicating if any facts were dropped.
        knowledge_gaps: Claims that could not be verified (NOT_SUPPORTED/UNCERTAIN).
        coverage_gaps: Original sub-questions (from original_plan) with no
            supporting evidence at all — set by the Critic.
        gap_queries: Targeted search queries generated by the Reflector to fill gaps.
        verified_facts: List[dict]
        iteration_count: int  # Loop-safety counter for fact-checker re-search cycles
        active_node: str
        require_approval: bool  # Pause at plan_gate for human plan review before Scout runs.
    """
    session_id: str
    query: str
    plan: List[dict]
    original_plan: List[dict]
    scraped_data: Annotated[List[dict], operator.add]
    structured_evidence: List[dict]
    source_map: Annotated[dict, lambda d1, d2: {**d1, **d2}]
    backend_health: dict
    critique: str
    report: str
    re_search_required: bool
    knowledge_gap_detected: bool
    knowledge_gaps: List[str]
    coverage_gaps: List[str]
    gap_queries: List[dict]
    verified_facts: Annotated[List[dict], operator.add]
    consensus_findings: List[dict]   # Cross-source agreements (from Consensus node)
    contradictions: List[dict]       # Cross-source conflicts (from Consensus node)
    quality_score: dict              # Interim after the Verifier, final (with
                                      # contradiction_count) after Consensus
    iteration_count: int  # Loop-safety counter for fact-checker re-search cycles
    active_node: str
    require_approval: bool


class VerifiedFact(BaseModel):
    # Groq rejects a schema whose nested objects omit additionalProperties:false,
    # and a permissive schema also lets the model skip the wrapper and emit a bare
    # array, which fails the tool call. extra="forbid" emits it and prevents both.
    model_config = ConfigDict(extra="forbid")

    claim: str
    source_url: str
    source_excerpt: str
    source_id: str = ""
    credibility_score: float = 0.4
    source_type: str = "Unverified/Web"
    support_level: Literal["SUPPORTED", "PARTIALLY_SUPPORTED", "NOT_SUPPORTED", "UNCERTAIN"]
    confidence: float

class VerifiedFactBatch(BaseModel):
    """Batch of verified facts — returned by a single LLM call."""
    model_config = ConfigDict(extra="forbid")

    results: List[VerifiedFact] = Field(
        description="List of verified facts with support levels and confidence scores."
    )

class SearchIntent(BaseModel):
    model_config = ConfigDict(extra="forbid")

    query: str = Field(description="The specific search query.")
    mode: Literal["TRUSTED_ONLY", "TRUSTED_FIRST", "MIXED"] = Field(
        description="TRUSTED_ONLY for hard science, TRUSTED_FIRST for broad analysis, MIXED for news/market."
    )

class ResearchPlan(BaseModel):
    """Output schema for the Librarian node."""
    model_config = ConfigDict(extra="forbid")

    search_queries: List[SearchIntent] = Field(
        description="List of 3-5 highly specific search queries and their optimal search modes."
    )


class FactCheckResult(BaseModel):
    """Output schema for the Critic node."""
    model_config = ConfigDict(extra="forbid")

    status: Literal["sufficient", "gaps_found"] = Field(
        description="Indicates if the current evidence is sufficient or if more research is required."
    )
    new_queries: List[SearchIntent] = Field(
        default_factory=list,
        description="If gaps are found, provide 1-3 highly specific dynamic follow-up queries."
    )
    critique: str = Field(
        description="Explanation of what is missing, any contradictions found, or why re-search is needed."
    )
